[package]
name = "keyrc"
version = "0.1.1"
description = "A lightweight native GTK keystroke overlay"
authors = ["baiyuechu"]
edition = "2021"
license = "MIT"

[dependencies]
gtk = "0.18"
libappindicator = "0.9"
rdev = "0.5"
toml = "0.9.8"

[profile.release]
codegen-units = 1
lto = "thin"
panic = "abort"
strip = true
