# ~/.config/keyrc/config.toml
[general]
mode = "keys_only" # "full" also displays the modifier row.

[keymap]
toggle_mode = "Ctrl+Alt+M"

[colors]
active_bg = "#121c29"
active_fg = "#719cd6"
key_text = "#c0c8d5"
background = "#192330"
border = "#252f3c"
